#!/usr/bin/env python3
"""S17: transport a .cof certificate of cell k along a symmetry g of the input (g in the dihedral group generated by the body
swaps (12),(34) and (13)(24); g exchanging {1,2}<->{3,4} also swaps the masses a<->b) to a certificate of cell g(k).
Pure text/arith transform; the OUTPUT is an ordinary .cof that verify.py checks from scratch (no trust in this script):
  cell g(k); subset: S_t -> pi(S_t) with g(f_{S_t}) = lam_t f_{pi(S_t)}; vars: v_j -> g(v_j) in the same positions (U,u fixed),
  so exponent vectors are unchanged; coefficients a<->b if swapped; cofactor t multiplied by lam_t; rhs a<->b if swapped.
usage: transport.py IN.cof TARGET_CELL OUT.cof"""
import sys,os,json
from fractions import Fraction
import verify as V
import flint
def gelems():
    s1={1:2,2:1,3:3,4:4,5:5}; s2={1:1,2:2,3:4,4:3,5:5}; sg={1:3,2:4,3:1,4:2,5:5}
    G={tuple(sorted({i:i for i in range(1,6)}.items()))}; fr=[dict(G.pop())]; G=set(); out=[]
    seen=set()
    while fr:
        h=fr.pop(); key=tuple(sorted(h.items()))
        if key in seen: continue
        seen.add(key); out.append(h)
        for s in (s1,s2,sg): fr.append({i:s[h[i]] for i in h})
    return out
def run(fin,target,fout):
    rv0,F0=V.load_sys(); rays,cells=V.read_fan(os.path.join(V.N5,'fan.out'))
    L=open(fin).read().split('\n'); k=int(L[0].split()[1]); hdr=L[1:7]
    sysname=L[1].strip() if L[1].startswith('system') else None
    rv,F={'system F+G':V.augment,'system F+G+H':V.augmentH}.get(sysname,lambda a,b:(a,b))(rv0,F0)
    rix={tuple(x):i for i,x in enumerate(rays)}; cix={tuple(sorted(c)):j for j,c in enumerate(cells)}
    for g in gelems():
        pairs=[(int(v[1]),int(v[2])) for v in rv0]; idx={p:j for j,p in enumerate(pairs)}
        P=[idx[tuple(sorted((g[i],g[j])))] for (i,j) in pairs]
        def ap(e):
            o=list(e)
            for j in range(10): o[P[j]]=e[j]
            return tuple(o)
        rm=[rix[ap(x)] for x in rays]; gk=cix[tuple(sorted(rm[i] for i in cells[k]))]
        if gk!=target: continue
        swap=g[1] in (3,4)
        sw=(lambda s: s.translate(str.maketrans('ab','ba'))) if swap else (lambda s:s)
        def img(f): return {ap(m):{((eb,ea) if swap else (ea,eb)):c for (ea,eb),c in d.items()} for m,d in f.items()}
        def lam_pi(i):
            fi=img(F[i])
            for j,fj in enumerate(F):
                if set(fj)!=set(fi): continue
                m0=next(iter(fi)); ab0=next(iter(fi[m0]))
                if ab0 not in fj[m0]: continue
                l=Fraction(fi[m0][ab0])/Fraction(fj[m0][ab0])
                if all(set(fi[m])==set(fj[m]) and all(Fraction(fi[m][x])==l*fj[m][x] for x in fi[m]) for m in fi): return l,j
            raise SystemExit('generator image not found')
        out=[]; t=None; lam=None
        for n,line in enumerate(L):
            if n==0: out.append('cell %d'%target); continue
            s=line.strip()
            if s.startswith('subset '):
                S=[int(x) for x in s[7:].split(',')]; LP=[lam_pi(i) for i in S]; lam=[x[0] for x in LP]
                out.append('subset '+','.join(str(x[1]) for x in LP)); continue
            if s.startswith('vars ') or s.startswith('even '):
                vs=s.split()[1].split(',')
                nv=[('r%d%d'%tuple(sorted((g[int(v[1])],g[int(v[2])]))) if v[0]=='r' and len(v)==3 else v) for v in vs]
                out.append(s.split()[0]+' '+','.join(nv)); continue
            if s.startswith('rhs '):
                out.append('rhs '+(s[4:] if s[4:].startswith('prod^') else sw(s[4:]))); continue
            if s.startswith('#'): t=int(s[1:])-1; out.append(s); continue
            if '|' in s and t is not None:
                num,den,ex=s.split('|'); l=lam[t] if t<len(lam) else Fraction(1)
                num=sw(num); den=sw(den)
                if l!=1:
                    ctx=flint.fmpq_mpoly_ctx.get(('a','b'),'lex')
                    num=(V.parse_poly(num,ctx,['a','b'])*flint.fmpq(l.numerator,l.denominator)).str().replace(' ','')
                out.append('|'.join([num,den,ex])); continue
            out.append(line)
        open(fout,'w').write('\n'.join(out)); print('transported cell',k,'->',target,'swap',swap,'lam',sorted(set(map(str,lam)))); return
    raise SystemExit('no group element maps %d to %d'%(k,target))
if __name__=='__main__': run(sys.argv[1],int(sys.argv[2]),sys.argv[3])
